# --- Stage 1: build dengan Vite
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json vite.config.js ./
RUN npm ci
COPY . .
RUN npm run build

# --- Stage 2: serve static files via nginx
FROM nginx:stable-alpine
# Hapus default config nginx
RUN rm -rf /usr/share/nginx/html/*
# Copy hasil build ke folder yang disajikan nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
