# Gunakan base image Node.js yang sesuai untuk Vite.
FROM node:20-alpine AS development

# Tentukan direktori kerja di dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json (jika ada)
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin sisa kode aplikasi Anda
COPY . .

# Vite secara default berjalan di port 5173.
# Opsi --host diperlukan agar server Vite dapat diakses dari luar container.
EXPOSE 5173

# Command untuk menjalankan server development Vite
CMD [ "npm", "run", "dev", "--", "--host" ]