# Stage 1: Build React app
FROM node:18-alpine AS build

WORKDIR /usr/src/app/frontend

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Serve app with Nginx
FROM nginx:stable-alpine
COPY --from=build /usr/src/app/frontend/dist /usr/share/nginx/html

# Salin konfigurasi Nginx kustom jika ada (opsional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]