FROM node:20-alpine AS development

# Tentukan direktori kerja di dalam container
WORKDIR /usr/src/app

# Salin package.json dan package-lock.json 
COPY package*.json ./

# Install dependencies
RUN npm install

# Salin sisa kode aplikasi
COPY . .

# Backend Anda menggunakan nodemon untuk development, yang sudah ada di devDependencies.
# Pastikan port yang diekspos sesuai dengan port yang didengarkan aplikasi Express Anda di app.js
# Biasanya 3000, 5000, atau 8000. Saya asumsikan 5000 untuk contoh ini.
# Anda mungkin perlu mengaturnya melalui variabel lingkungan di docker-compose.yml
EXPOSE 5000

# Command untuk menjalankan aplikasi menggunakan script "dev" dari package.json
CMD [ "npm", "run", "dev" ]